linters:
  enable-all: true
  disable:
    - depguard
    - nosnakecase
    - scopelint
    - ifshort
    - varcheck
    - deadcode
    - maligned
    - interfacer
    - golint
    - exhaustivestruct
    - structcheck

linters-settings:
  cyclop:
    max-complexity: 12
